# **Les 2 - Lineaire Regressie**

**Doel:** Voorspel de prijs van tweedehands auto's op basis van enkele kenmerken.
    
***Stel jezelf de volgende vragen?***  
*- Welke parameter tracht je te voorspellen?*  
*- Wat voor type parameter is dit?*  
*- Wat zou een goede techniek zijn om deze te analyseren?*

## Stap 1: Libraries

In [51]:
import re
import numpy as np
import pandas as pd
# import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import joblib

## Stap 2: Data

In [52]:
# Laden
df1 = pd.read_csv("second_hand_cars_deel1.csv")
df2 = pd.read_csv("second_hand_cars_deel2.csv")

# Chassisnummer gelijk benoemen en datasets samenvoegen
df1 = df1.rename(columns={"CHASSISNUMMER": "chassisnummer"})
df = pd.merge(df1, df2, on="chassisnummer")

# Tekst omzetten naar getallen
def naar_getal(waarde):
    if pd.isna(waarde):
        return np.nan

    tekst = str(waarde).replace(".", "")
    getallen = re.findall(r"\d+(?:,\d+)?", tekst)

    if len(getallen) == 0:
        return np.nan

    getallen = [float(x.replace(",", ".")) for x in getallen]
    return np.mean(getallen)

numerieke_kolommen = [
    "CC/Batterij",
    "Oorspronkelijke Catalogusprijs",
    "Huidige Nieuwprijs",
    "Leeftijd",
    "Kilometerstand",
    "Verbruik",
    "Topsnelheid",
    "Vermogen",
    "Koppel",
    "Huidige Verkoopprijs"
]

for kolom in numerieke_kolommen:
    df[kolom] = df[kolom].apply(naar_getal)

# Duidelijke foutieve verkoopprijs verwijderen
df.loc[df["Huidige Verkoopprijs"] > 100000, "Huidige Verkoopprijs"] = np.nan

# EDA
print(df.shape)
display(df.head())
display(df.describe())

(1000, 16)

,chassisnummer,Company Naam,Auto Namen,Motor,CC/Batterij,Oorspronkelijke Catalogusprijs,Huidige Nieuwprijs,Leeftijd,Kilometerstand,Score,Conditie,Verbruik,Topsnelheid,Vermogen,Koppel,Huidige Verkoopprijs
0,1HGYAKH1Z6C000000,VOLKSWAGEN,polo,1.0 TSI,999.0,18748.0,27937.0,3.0,78945.0,1,2,14.0,177.0,73.0,123.0,12296.0
1,WAUPAHTAGYU000001,Volkswagen,Golf,1.6 TDI,1598.0,20717.0,30137.0,6.0,NaN,5,9,9.0,148.0,NaN,95.0,9975.0
2,WBAHW3A30MF000002,toyota,YARIS,1.5 hybrid,1490.0,24045.0,26977.0,2.0,132538.0,2,8,NaN,181.0,53.0,97.0,7539.0
3,VF18MDD4W31000003,Toyota,COROLLA,1.8 hybrid,1798.0,20090.0,25283.0,4.0,101065.0,4,3,11.0,197.0,54.0,116.0,8550.0
4,ZARU9NV4X5W000004,Ford,fiesta,1.0 ECOBOOST,998.0,24199.0,28397.0,6.0,61559.0,3,9,12.0,160.0,53.0,105.0,18589.0

,CC/Batterij,Oorspronkelijke Catalogusprijs,Huidige Nieuwprijs,Leeftijd,Kilometerstand,Score,Conditie,Verbruik,Topsnelheid,Vermogen,Koppel,Huidige Verkoopprijs
count,946.000000,963.000000,972.000000,1000.000000,9.770000e+02,1000.000000,1000.000000,953.000000,946.000000,968.000000,937.000000,971.000000
mean,1272.413319,21050.933541,27982.431070,4.561000,1.127825e+05,2.988000,5.592000,11.625393,166.935518,84.798554,103.801494,10727.224511
std,270.850640,2044.307080,1993.821944,1.719079,3.977857e+05,1.402791,2.824449,2.226951,19.380049,20.545903,20.959237,4427.376040
min,898.000000,17509.000000,24501.000000,2.000000,3.500000e+03,1.000000,1.000000,8.000000,135.000000,50.000000,68.000000,0.000000
25%,999.000000,19203.500000,26304.500000,3.000000,7.432100e+04,2.000000,3.000000,10.000000,150.000000,67.000000,85.000000,7210.000000
50%,1199.000000,21038.000000,27941.000000,5.000000,9.934000e+04,3.000000,6.000000,12.000000,166.000000,84.500000,104.000000,10672.000000
75%,1499.000000,22832.500000,29674.500000,6.000000,1.250450e+05,4.000000,8.000000,13.000000,184.000000,102.000000,122.000000,14467.500000
max,1798.000000,24495.000000,31493.000000,7.000000,1.250000e+07,5.000000,10.000000,15.000000,200.000000,120.000000,140.000000,20449.000000

## Stap 3: Preprocessing

In [53]:
# Numerieke kolommen
num_features = [
    "CC/Batterij",
    "Oorspronkelijke Catalogusprijs",
    "Huidige Nieuwprijs",
    "Leeftijd",
    "Kilometerstand",
    "Score",
    "Conditie",
    "Verbruik",
    "Topsnelheid",
    "Vermogen",
    "Koppel"
]

# Categorische kolommen
cat_features = [
    "Company Naam",
    "Auto Namen",
    "Motor"
]

# Preprocessing numerieke & categorische data
num_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

cat_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

# In 1 preprocessor
preprocessor = ColumnTransformer([
    ("num", num_transformer, num_features),
    ("cat", cat_transformer, cat_features)
])

## Stap 4: Splitsen in Test en Training

In [54]:
df = df.dropna(subset=["Huidige Verkoopprijs"])

X = df[num_features + cat_features]
y = df["Huidige Verkoopprijs"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Stap 5: ML Pipeline

In [55]:
pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", LinearRegression())
])

## Stap 6: Train het model

In [56]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['CC/Batterij',
                                                   'Oorspronkelijke '
                                                   'Catalogusprijs',
                                                   'Huidige Nieuwprijs',
                                                   'Leeftijd', 'Kilometerstand',
                                                   'Score', 'Conditie',
                                                   'Verbruik', 'Topsnelheid',
                                                   'Vermogen', 'Koppel']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Company Naam', 'Auto Namen',
                                                   'Motor'])])),
                ('regressor', LinearRegression())])

## Stap 7: Evaluatie

In [57]:
y_pred = pipeline.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MSE:", mse)
print("RMSE:", rmse)
print("R²:", r2)

MSE: 22288663.24711781
RMSE: 4721.087083195755
R²: -0.1564046586332033

### *Intermezzo: Sla het model op*

In [58]:
# Sla de pipeline op en laad deze opnieuw
joblib.dump(pipeline, "linear_regression_pipeline.pkl")
loaded_pipeline = joblib.load("linear_regression_pipeline.pkl")

## Stap 8: Voorspelling

In [59]:
nieuwe_auto = pd.DataFrame([{
    "CC/Batterij": 1499,
    "Oorspronkelijke Catalogusprijs": 24000,
    "Huidige Nieuwprijs": 28000,
    "Leeftijd": 5,
    "Kilometerstand": 65000,
    "Score": 4,
    "Conditie": 8,
    "Verbruik": 14,
    "Topsnelheid": 190,
    "Vermogen": 150,
    "Koppel": 220,
    "Company Naam": "Volkswagen",
    "Auto Namen": "Golf",
    "Motor": "1.5 hybrid"
}])

nieuwe_auto

,CC/Batterij,Oorspronkelijke Catalogusprijs,Huidige Nieuwprijs,Leeftijd,Kilometerstand,Score,Conditie,Verbruik,Topsnelheid,Vermogen,Koppel,Company Naam,Auto Namen,Motor
0,1499,24000,28000,5,65000,4,8,14,190,150,220,Volkswagen,Golf,1.5 hybrid

In [60]:
geschatte_prijs = loaded_pipeline.predict(nieuwe_auto)

print(f"Geschatte verkoopprijs voor de testauto: € {geschatte_prijs[0]:,.2f}")

Geschatte verkoopprijs voor de testauto: € 12,883.75